### ISSUE TITLE
Class 'backend\assets\AppAsset' not found

### ISSUE THREAD

**Issue by jashirouprotips** [ayrozjlc/yii2-adminlte3-asset#1]
Hi,

I tried to config this adminlte3 in my Yii2 Proyect and I have a issue:

After install and config all files like in the "Quick Start" doc I have this problem.

![image](https://user-images.githubusercontent.com/29470002/83555231-356eed80-a4cb-11ea-903f-7d2940522557.png)

Please help...

Thanks in advance!

**Comment by ayrozjlc** [comment]
Apparently you have the basic template installed

In line 5 change backend for app

I hope it is solved.

**Comment by jashirouprotips** [comment]
> Apparently you have the basic template installed
> 
> In line 5 change backend for app
> 
> I hope it is solved.

Thanks did work...

But now how can I see the login web-page?

![image](https://user-images.githubusercontent.com/29470002/83569696-1e87c580-a4e2-11ea-93fa-24eeb27750f4.png)
